//! `init.sh` reader/runner.
//!
//! [`InitScript`] handles the `init.sh` artifact described in SPEC §9.6
//! for harnessed runs. The script content itself is generated by the
//! `initializer` subagent (a future issue); this module only **reads**
//! the file and **runs** it within sandbox constraints.
//!
//! ## Why a separate type?
//!
//! Keeping `InitScript` distinct from `FeatureList` makes the
//! harnessed-only artifact set self-documenting and lets us reuse the
//! same `tmg_sandbox::SandboxContext` pipeline that backs all other
//! shell-execution paths in tsumugi.

use std::path::{Path, PathBuf};
use std::time::Duration;

use tmg_sandbox::{CommandOutput, SandboxContext, SandboxError};

/// Output of a single `init.sh` invocation.
///
/// Wraps [`tmg_sandbox::CommandOutput`] with an explicit `timed_out`
/// flag so callers can distinguish a timeout from a non-zero exit code
/// without inspecting the original error variant.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InitScriptOutput {
    /// Whether the script was killed because it exceeded the per-run
    /// timeout.
    pub timed_out: bool,
    /// Captured stdout. Empty when `timed_out` is `true`.
    pub stdout: String,
    /// Captured stderr. Empty when `timed_out` is `true`.
    pub stderr: String,
    /// Exit code (`-1` when the process was killed by a signal or
    /// timed out before producing one).
    pub exit_code: i32,
}

impl InitScriptOutput {
    /// Construct from a [`CommandOutput`] (no timeout).
    fn from_command(output: CommandOutput) -> Self {
        Self {
            timed_out: false,
            stdout: output.stdout,
            stderr: output.stderr,
            exit_code: output.exit_code,
        }
    }

    /// Construct a timeout result with no captured output.
    const fn timeout() -> Self {
        Self {
            timed_out: true,
            stdout: String::new(),
            stderr: String::new(),
            exit_code: -1,
        }
    }

    /// Return `true` when the script exited with code 0 and was not
    /// killed by a timeout.
    #[must_use]
    pub fn success(&self) -> bool {
        !self.timed_out && self.exit_code == 0
    }

    /// Last `n` lines of stdout, joined with `\n`. Useful for
    /// surfacing a tail in `session_bootstrap` without dumping
    /// kilobytes into the model context.
    #[must_use]
    pub fn tail_stdout(&self, n: usize) -> String {
        tail_lines(&self.stdout, n)
    }

    /// Last `n` lines of stderr, joined with `\n`.
    #[must_use]
    pub fn tail_stderr(&self, n: usize) -> String {
        tail_lines(&self.stderr, n)
    }
}

/// Handle for a run's `init.sh`.
///
/// Cloning is cheap (path-only).
#[derive(Debug, Clone)]
pub struct InitScript {
    path: PathBuf,
}

impl InitScript {
    /// Create a handle for the file at `path` without touching disk.
    #[must_use]
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { path: path.into() }
    }

    /// Borrow the on-disk path.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Whether the script exists on disk.
    #[must_use]
    pub fn exists(&self) -> bool {
        self.path.exists()
    }

    /// Run the script via the supplied [`SandboxContext`].
    ///
    /// The script is executed by passing its absolute path to `sh -c`,
    /// which runs the file as a shell script. The configured
    /// `SandboxContext` provides the underlying timeout / OOM /
    /// filesystem restrictions; this function additionally enforces
    /// the per-call `timeout` parameter using
    /// [`tokio::time::timeout`] so callers do not have to mutate the
    /// shared sandbox configuration.
    ///
    /// On timeout, `InitScriptOutput::timed_out` is set to `true` and
    /// `stdout` / `stderr` are empty.
    ///
    /// # Errors
    ///
    /// - [`InitScriptError::NotFound`] when the script does not exist.
    /// - [`InitScriptError::Sandbox`] for non-timeout sandbox errors
    ///   (spawn failure, I/O error reading pipes).
    pub async fn run(
        &self,
        sandbox: &SandboxContext,
        timeout: Duration,
    ) -> Result<InitScriptOutput, InitScriptError> {
        if !self.exists() {
            return Err(InitScriptError::NotFound {
                path: self.path.clone(),
            });
        }

        // Quote the path defensively for `sh -c` consumption. Single
        // quotes around the path are sufficient because the path itself
        // never contains a single quote in practice (run directories
        // are tsumugi-generated short hex ids); we still escape any
        // embedded `'` by closing the quoted region, inserting an
        // escaped quote, and reopening — the standard shell idiom.
        let escaped = shell_escape(&self.path.display().to_string());
        let command = format!("sh {escaped}");

        let result = tokio::time::timeout(timeout, sandbox.run_command(&command)).await;
        match result {
            Ok(Ok(output)) => Ok(InitScriptOutput::from_command(output)),
            // Sandbox itself reported a timeout (its inner timeout fired
            // before our outer one) **or** our outer `tokio::time::timeout`
            // fired first; both are surfaced as a "soft" timeout.
            Ok(Err(SandboxError::Timeout { .. })) | Err(_) => Ok(InitScriptOutput::timeout()),
            Ok(Err(other)) => Err(InitScriptError::Sandbox(other)),
        }
    }
}

/// Errors raised by [`InitScript::run`].
///
/// Sandbox-level timeouts are **not** errors here — they surface via
/// `InitScriptOutput::timed_out` so the caller can render them in the
/// same data structure as a successful run.
#[derive(Debug, thiserror::Error)]
pub enum InitScriptError {
    /// The script path does not exist on disk.
    #[error("init.sh not found at {}", path.display())]
    NotFound {
        /// Path that was looked up.
        path: PathBuf,
    },

    /// Underlying sandbox error (other than timeout).
    #[error("sandbox error running init.sh: {0}")]
    Sandbox(#[from] SandboxError),
}

/// Escape a path so it can be safely embedded inside single quotes for
/// `sh -c`.
fn shell_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// Return the last `n` lines of `text`, joined by `\n`.
fn tail_lines(text: &str, n: usize) -> String {
    if n == 0 || text.is_empty() {
        return String::new();
    }
    let lines: Vec<&str> = text.lines().collect();
    let start = lines.len().saturating_sub(n);
    lines[start..].join("\n")
}

#[cfg(test)]
#[expect(clippy::panic, reason = "test assertions use panic-based macros")]
mod tests {
    use super::*;

    use tmg_sandbox::{SandboxConfig, SandboxMode};

    fn sandbox_for(workspace: &Path) -> SandboxContext {
        let config = SandboxConfig::new(workspace).with_mode(SandboxMode::Full);
        SandboxContext::new(config)
    }

    #[tokio::test]
    async fn missing_script_returns_not_found() {
        let tmp = tempfile::tempdir().unwrap_or_else(|e| panic!("{e}"));
        let path = tmp.path().join("init.sh");
        let script = InitScript::new(path);
        let sandbox = sandbox_for(tmp.path());
        let result = script.run(&sandbox, Duration::from_secs(1)).await;
        assert!(matches!(result, Err(InitScriptError::NotFound { .. })));
    }

    #[tokio::test]
    async fn exists_reports_correctly() {
        let tmp = tempfile::tempdir().unwrap_or_else(|e| panic!("{e}"));
        let path = tmp.path().join("init.sh");
        let script = InitScript::new(&path);
        assert!(!script.exists());
        std::fs::write(&path, "#!/bin/sh\necho hi\n").unwrap_or_else(|e| panic!("{e}"));
        assert!(script.exists());
    }

    #[tokio::test]
    async fn successful_run_captures_stdout() {
        let tmp = tempfile::tempdir().unwrap_or_else(|e| panic!("{e}"));
        let path = tmp.path().join("init.sh");
        std::fs::write(&path, "#!/bin/sh\necho hello-from-init\n")
            .unwrap_or_else(|e| panic!("{e}"));
        let script = InitScript::new(&path);
        let sandbox = sandbox_for(tmp.path());

        let output = script
            .run(&sandbox, Duration::from_secs(10))
            .await
            .unwrap_or_else(|e| panic!("{e}"));
        assert!(output.success(), "{output:?}");
        assert!(!output.timed_out);
        assert_eq!(output.exit_code, 0);
        assert!(
            output.stdout.contains("hello-from-init"),
            "{}",
            output.stdout
        );
    }

    #[tokio::test]
    async fn nonzero_exit_is_not_timeout() {
        let tmp = tempfile::tempdir().unwrap_or_else(|e| panic!("{e}"));
        let path = tmp.path().join("init.sh");
        std::fs::write(&path, "#!/bin/sh\nexit 42\n").unwrap_or_else(|e| panic!("{e}"));
        let script = InitScript::new(&path);
        let sandbox = sandbox_for(tmp.path());

        let output = script
            .run(&sandbox, Duration::from_secs(5))
            .await
            .unwrap_or_else(|e| panic!("{e}"));
        assert!(!output.timed_out);
        assert!(!output.success());
        assert_eq!(output.exit_code, 42);
    }

    /// Acceptance criterion: `sleep 60` with a 1-second timeout sets
    /// `timed_out = true`.
    #[tokio::test]
    async fn long_running_script_triggers_timeout() {
        let tmp = tempfile::tempdir().unwrap_or_else(|e| panic!("{e}"));
        let path = tmp.path().join("init.sh");
        std::fs::write(&path, "#!/bin/sh\nsleep 60\n").unwrap_or_else(|e| panic!("{e}"));
        let script = InitScript::new(&path);
        let sandbox = sandbox_for(tmp.path());

        let output = script
            .run(&sandbox, Duration::from_secs(1))
            .await
            .unwrap_or_else(|e| panic!("{e}"));
        assert!(output.timed_out, "expected timeout, got {output:?}");
        assert!(!output.success());
    }

    #[test]
    fn tail_lines_returns_last_n() {
        let text = "a\nb\nc\nd\ne\n";
        assert_eq!(tail_lines(text, 2), "d\ne");
        assert_eq!(tail_lines(text, 10), "a\nb\nc\nd\ne");
        assert_eq!(tail_lines("", 3), "");
        assert_eq!(tail_lines("only one line", 5), "only one line");
        assert_eq!(tail_lines(text, 0), "");
    }

    #[test]
    fn shell_escape_handles_single_quotes() {
        assert_eq!(shell_escape("plain"), "'plain'");
        assert_eq!(shell_escape("with space"), "'with space'");
        assert_eq!(shell_escape("o'brien"), "'o'\\''brien'");
    }

    #[test]
    fn output_helpers_truncate_correctly() {
        let output = InitScriptOutput {
            timed_out: false,
            stdout: "1\n2\n3\n4\n5\n".to_owned(),
            stderr: "e1\ne2\ne3\n".to_owned(),
            exit_code: 0,
        };
        assert_eq!(output.tail_stdout(2), "4\n5");
        assert_eq!(output.tail_stderr(1), "e3");
    }
}
